version: "3.8"

services:
  if-nginx:
    container_name: if-nginx
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}
    depends_on:
      - if-php-fpm
    restart: unless-stopped

  if-php-fpm:
    container_name: if-php-fpm
    build:
      context: .
      dockerfile: docker/php/8.2/fpm/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - if-mysql

  if-php-cli:
    container_name: if-php-cli
    build:
      context: .
      dockerfile: docker/php/8.2/cli/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - if-mysql

  if-mysql:
    container_name: if-mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - if-mysql-db-data:/bitnami/mysql/data
    restart: unless-stopped

networks:
  default:
    external: true
    name: if-network

volumes:
  if-mysql-db-data:
